"""Core helpers for the knowledge base: YAML subset parsing, loading, rendering.

Stdlib only, by design. No PyYAML, no jsonschema, no network. The cost of that choice is
a restricted YAML subset (documented in AGENTS.md section 4); the benefit is that any agent
on any host can validate the whole knowledge base with `python3` and nothing else.
"""

from __future__ import annotations

import hashlib
import os
import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

PAGE_TYPES = ("concept", "entity", "topic", "claim", "question", "synthesis")
DIR_FOR_TYPE = {
    "concept": "concepts",
    "entity": "entities",
    "topic": "topics",
    "claim": "claims",
    "question": "questions",
    "synthesis": "syntheses",
}
TYPE_FOR_DIR = {v: k for k, v in DIR_FOR_TYPE.items()}

PAGE_STATUS = ("draft", "active", "superseded", "deprecated")
VISIBILITY = ("public", "internal", "restricted")
CONFIDENCE = ("high", "medium", "low")
SOURCE_STATUS = ("active", "reference-only", "deprecated")

REQUIRED_PAGE_KEYS = (
    "id", "page_type", "status", "owner", "visibility",
    "confidence", "summary", "updated_at", "sources",
)
OPTIONAL_PAGE_KEYS = ("related", "supersedes", "tags", "review_required")

REQUIRED_MANIFEST_KEYS = ("id", "title", "source_type", "status", "captured_at")
OPTIONAL_MANIFEST_KEYS = (
    "original_url", "raw_uri", "sha256", "media_type", "bytes", "license", "notes",
)

BODY_SECTIONS = ("Definition", "Current Understanding", "Disputed or Uncertain", "Evidence")

GENERATED_MARKER = "<!-- GENERATED by `bin/kb reindex`. Do not edit by hand. -->"

# Files that are a pure function of the pages and manifests. check_index proves they match
# byte-for-byte, so no content can be smuggled through them and team ownership adds nothing —
# while requiring it would stop any team but one from ever running `bin/kb reindex`.
GENERATED_PATHS = ("wiki/index.md", "sources/index.md")


class KbError(Exception):
    """A malformed input. Always carries a location the author can act on."""


# --------------------------------------------------------------------------- yaml


def _scalar(raw: str, where: str, lineno: int):
    v = raw.strip()
    if v[:1] in ("'", '"'):
        q = v[0]
        end = v.rfind(q)
        if end <= 0:
            raise KbError(f"{where}:{lineno}: unterminated {q} quote")
        return v[1:end]
    # an unquoted value ends at an inline comment
    if " #" in v:
        v = v.split(" #", 1)[0].rstrip()
    if v.startswith("[") and v.endswith("]"):
        inner = v[1:-1].strip()
        if not inner:
            return []
        return [_scalar(part, where, lineno) for part in inner.split(",")]
    if v in ("null", "~", ""):
        return None
    if v == "true":
        return True
    if v == "false":
        return False
    return v


def parse_yaml_subset(text: str, where: str = "<yaml>") -> dict:
    """Parse the supported subset: flat `key: value`, `key:` + `- item` lists, comments.

    Anything else — nested mappings, multi-line strings, anchors — is an error rather than
    a silent misparse. `key:` with nothing after it is an empty list; use `null` for an
    absent scalar.
    """
    data: dict = {}
    cur_key: str | None = None
    for lineno, raw in enumerate(text.splitlines(), 1):
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        if raw[:1] in (" ", "\t"):
            item = raw.strip()
            if not item.startswith("- "):
                raise KbError(
                    f"{where}:{lineno}: indented lines must be '- item' "
                    f"(nested maps are not supported)"
                )
            if cur_key is None:
                raise KbError(f"{where}:{lineno}: list item with no preceding key")
            if not isinstance(data.get(cur_key), list):
                raise KbError(
                    f"{where}:{lineno}: '{cur_key}' already has a scalar value; "
                    f"it cannot also be a list"
                )
            data[cur_key].append(_scalar(item[2:], where, lineno))
            continue
        if ":" not in raw:
            raise KbError(f"{where}:{lineno}: expected 'key: value', got {raw.strip()!r}")
        key, _, val = raw.partition(":")
        key = key.strip()
        if not key:
            raise KbError(f"{where}:{lineno}: empty key")
        if key in data:
            raise KbError(f"{where}:{lineno}: duplicate key '{key}'")
        if val.strip() == "" or val.strip().startswith("#"):
            data[key] = []
            cur_key = key
        else:
            data[key] = _scalar(val, where, lineno)
            cur_key = None
    return data


def split_frontmatter(text: str, where: str) -> tuple[dict, str]:
    """Return (frontmatter dict, body). The file must open with a `---` fence."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise KbError(f"{where}:1: file must start with a '---' frontmatter fence")
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            fm = "\n".join(lines[1:i])
            return parse_yaml_subset(fm, where), "\n".join(lines[i + 1:])
    raise KbError(f"{where}: frontmatter fence is never closed")


# --------------------------------------------------------------------------- globs


def glob_to_regex(pattern: str) -> re.Pattern:
    """`*` matches within one path segment, `**` crosses segments, `?` matches one char."""
    out, i = [], 0
    while i < len(pattern):
        c = pattern[i]
        if c == "*":
            if pattern[i + 1: i + 2] == "*":
                out.append(".*")
                i += 2
                continue
            out.append("[^/]*")
        elif c == "?":
            out.append("[^/]")
        else:
            out.append(re.escape(c))
        i += 1
    return re.compile("^" + "".join(out) + "$")


def path_matches(path: str, patterns) -> bool:
    return any(glob_to_regex(p).match(path) for p in patterns or ())


# --------------------------------------------------------------------------- loading


class Page:
    def __init__(self, path: Path, meta: dict, body: str):
        self.path = path
        self.meta = meta
        self.body = body

    @property
    def rel(self) -> str:
        return self.path.relative_to(ROOT).as_posix()

    @property
    def id(self) -> str:
        return self.meta.get("id") or ""

    @property
    def page_type(self) -> str:
        return self.meta.get("page_type") or ""

    def link_from_wiki(self) -> str:
        return self.path.relative_to(ROOT / "wiki").as_posix()


class Manifest:
    def __init__(self, path: Path, meta: dict):
        self.path = path
        self.meta = meta

    @property
    def rel(self) -> str:
        return self.path.relative_to(ROOT).as_posix()

    @property
    def id(self) -> str:
        return self.meta.get("id") or ""


def wiki_page_paths() -> list[Path]:
    wiki = ROOT / "wiki"
    if not wiki.is_dir():
        return []
    skip = {wiki / "index.md", wiki / "log.md"}
    return sorted(p for p in wiki.rglob("*.md") if p not in skip)


def load_pages() -> tuple[list[Page], list[str]]:
    pages, errors = [], []
    for p in wiki_page_paths():
        rel = p.relative_to(ROOT).as_posix()
        try:
            meta, body = split_frontmatter(p.read_text(encoding="utf-8"), rel)
        except KbError as e:
            errors.append(str(e))
            continue
        pages.append(Page(p, meta, body))
    return pages, errors


def load_manifests() -> tuple[list[Manifest], list[str]]:
    out, errors = [], []
    d = ROOT / "sources" / "manifests"
    if not d.is_dir():
        return out, errors
    for p in sorted(d.glob("*.yaml")):
        rel = p.relative_to(ROOT).as_posix()
        try:
            meta = parse_yaml_subset(p.read_text(encoding="utf-8"), rel)
        except KbError as e:
            errors.append(str(e))
            continue
        out.append(Manifest(p, meta))
    return out, errors


def load_governance(name: str) -> dict:
    p = ROOT / "governance" / name
    if not p.is_file():
        raise KbError(f"governance/{name} is missing")
    return parse_yaml_subset(p.read_text(encoding="utf-8"), f"governance/{name}")


def as_list(value) -> list:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    return [value]


# --------------------------------------------------------------------------- rendering


def render_wiki_index(pages: list[Page]) -> str:
    lines = ["# Wiki Index", "", GENERATED_MARKER, ""]
    lines.append(f"{len(pages)} pages. Catalog of what the wiki knows. "
                 "Chronology lives in [log.md](log.md).")
    lines.append("")
    for ptype in PAGE_TYPES:
        group = sorted((p for p in pages if p.page_type == ptype), key=lambda p: p.id)
        if not group:
            continue
        lines.append(f"## {DIR_FOR_TYPE[ptype].capitalize()}")
        lines.append("")
        for p in group:
            bits = [str(p.meta.get("owner", "?")),
                    f"confidence: {p.meta.get('confidence', '?')}",
                    str(p.meta.get("visibility", "?"))]
            if p.meta.get("status") != "active":
                bits.append(f"status: {p.meta.get('status')}")
            lines.append(
                f"- [{p.id}]({p.link_from_wiki()}) — {p.meta.get('summary', '')} "
                f"· {' · '.join(bits)}"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_sources_index(manifests: list[Manifest]) -> str:
    lines = ["# Source Index", "", GENERATED_MARKER, ""]
    lines.append(f"{len(manifests)} registered sources. Manifests are versioned; "
                 "the raw bytes they cite are immutable.")
    lines.append("")
    for m in sorted(manifests, key=lambda m: m.id):
        lines.append(
            f"- [{m.id}](manifests/{m.path.name}) — {m.meta.get('title', '')} "
            f"· {m.meta.get('source_type', '?')} · {m.meta.get('status', '?')}"
        )
    return "\n".join(lines).rstrip() + "\n"


# --------------------------------------------------------------------------- raw store


def main_root() -> Path:
    """The main repository root, even when running inside a linked worktree.

    A linked worktree's `.git` is a file pointing at `<main>/.git/worktrees/<name>`. The raw
    store and control state are shared, so they hang off the main root rather than off ROOT.
    Resolved by reading that file — no subprocess, so validation stays cheap.
    """
    dotgit = ROOT / ".git"
    if dotgit.is_file():
        text = dotgit.read_text(encoding="utf-8").strip()
        if text.startswith("gitdir:"):
            gitdir = Path(text.split(":", 1)[1].strip())
            for parent in gitdir.parents:
                if parent.name == ".git":
                    return parent.parent
    return ROOT


def raw_root() -> Path | None:
    env = os.environ.get("KB_RAW")
    if env:
        return Path(env)
    for candidate in (main_root() / ".raw", ROOT / ".raw"):
        if candidate.is_dir():
            return candidate
    return None


def raw_path_for(sha: str) -> Path | None:
    root = raw_root()
    if not root or len(sha) != 64:
        return None
    return root / "sha256" / sha[:2] / sha[2:4] / sha


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def is_iso_date(value) -> bool:
    if not isinstance(value, str):
        return False
    try:
        date.fromisoformat(value)
        return True
    except ValueError:
        return False


def is_iso_timestamp(value) -> bool:
    if not isinstance(value, str):
        return False
    v = value.replace("Z", "+00:00")
    try:
        from datetime import datetime
        datetime.fromisoformat(v)
        return True
    except ValueError:
        return False
